ComicMaster.CMS.Web/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

using ComicMaster.CMS.Common;
using ComicMaster.CMS.Common.Extentions;
using ComicMaster.CMS.Common.Infrastructure.Service;
using ComicMaster.CMS.Core;
using ComicMaster.CMS.Core.Interfaces;
using ComicMaster.CMS.Core.Models;

namespace ComicMaster.CMS.Web.Controllers
{
    public class ArticleController : ApiController
    {
        private readonly INewsService _newsService;

        public ArticleController()
            : this(new NewsService())
        {
        }

        public ArticleController(INewsService newsService)
        {
            _newsService = newsService;
        }

        // GET api/article
        [System.Web.Http.HttpGet]
        [Authorize(Roles = "Administrator, Content Editor")]
        public ServiceDataResponse<IList<dtoNews>> Get()
        {
            IList<dtoNews> _news = _newsService.GetAll().OrderByDescending(n => n.NewsDate).ToList();

            if (_news != null)
            {
                return new ServiceDataResponse<IList<dtoNews>>(_news);
            }
            else
            {
                ServiceDataResponse<IList<dtoNews>> fail = new ServiceDataResponse<IList<dtoNews>>();
                fail.data = null;
                fail.message = ResponseMessage.ApiFail;
                fail.success = false;

                return fail;
            }
        }

        // GET api/article/5
        [Authorize(Roles = "Administrator, Content Editor")]
        public HttpResponseMessage Get(int id)
        {
            dtoNews news = _newsService.Single(n => n.NewsId == id);

            if (news == null)
                return Request.CreateErrorResponse(HttpStatusCode.NotFound, "News article not found for the given id");
            else
                return Request.CreateResponse(HttpStatusCode.OK, news);
        }

        // POST api/article
        [HttpPost]
        [AcceptVerbs("GET", "POST")]        
        [Authorize(Roles = "Administrator, Content Editor")]
        public HttpResponseMessage Post(dtoNews news)
        {            
            news.Title = StringExtensions.CleanText(news.Title);

            string message = _newsService.AddNew(news);

            if (message == Constants.Success)
            {
                return Request.CreateResponse<string>(HttpStatusCode.Created, message);
            }
            else
            {
                return Request.CreateResponse<string>(HttpStatusCode.ExpectationFailed, message);
            }
        }

        // PUT api/article/5
        [HttpPut]
        [AcceptVerbs("GET", "POST", "PUT")]
        [Authorize(Roles = "Administrator, Content Editor")]
        public HttpResponseMessage Put(int id, dtoNews news)
        {
            news.NewsId = id;
            news.Title = StringExtensions.CleanText(news.Title);

            if (_newsService.UpdateNews(news) != Constants.Fail)
                return Request.CreateResponse(HttpStatusCode.OK);
            else
                return Request.CreateErrorResponse(HttpStatusCode.ExpectationFailed, "Unable to update the news article with the given ID");
        }

        // DELETE api/article/5
        [HttpDelete]
        [AcceptVerbs("GET", "POST", "PUT", "DELETE")]
        [Authorize(Roles = "Administrator, Content Editor")]
        public HttpResponseMessage Delete(int id)
        {
            var news = _newsService.Single(x => x.NewsId == id);

            if (news != null)
            {
                var response = _newsService.DeleteNews(news);

                if (response == Constants.Success)
                    return new HttpResponseMessage(HttpStatusCode.NoContent);
                else
                    return new HttpResponseMessage(HttpStatusCode.ExpectationFailed);
            }
            else
                return new HttpResponseMessage(HttpStatusCode.NotFound);
        }
    }
}

ComicMaster.CMS.Web/Controllers/BlogController.cs
using System;
using System.Configuration;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

using ComicMaster.CMS.Common;
using ComicMaster.CMS.Common.Infrastructure.Service;
using ComicMaster.CMS.Core;
using ComicMaster.CMS.Core.Interfaces;
using ComicMaster.CMS.Core.Models;
using ComicMaster.CMS.Web.Models;

namespace ComicMaster.CMS.Web.Controllers
{
    public class BlogController : ApiController
    {
        private readonly IPostService _postService;

        public BlogController()
            : this(new PostService())
        {            
        }

        public BlogController(IPostService postService)
        {
            _postService = postService;
        }

        // GET api/blog
        public ServiceDataResponse<PostViewModel> Get(int id, int? page)
        {
            int start = 1;
            int pageSize;

            if (page.HasValue)
                start = page.Value;

            if (int.TryParse(ConfigurationManager.AppSettings["PageSize"], out pageSize))
            {
                var posts = _postService.Posts(id, start - 1, pageSize);
                var totalPosts = _postService.Count();

                var postViewModel = new PostViewModel
                {
                    Posts = posts,
                    TotalPosts = totalPosts
                };

                if (postViewModel.Posts != null)
                    return new ServiceDataResponse<PostViewModel>(postViewModel);
                else
                {
                    ServiceDataResponse<PostViewModel> fail = new ServiceDataResponse<PostViewModel>();
                    fail.data = null;
                    fail.message = ResponseMessage.ApiFail;
                    fail.success = false;

                    return fail;
                }
            }

            return null;
        }

        // GET api/blog/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/blog
        public void Post([FromBody]string value)
        {
        }

        // PUT api/blog/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/blog/5
        public void Delete(int id)
        {
        }
    }
}

ComicMaster.CMS.Web/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

using ComicMaster.CMS.Common;
using ComicMaster.CMS.Common.Extentions;
using ComicMaster.CMS.Common.Security.Sessions;
using ComicMaster.CMS.Core;
using ComicMaster.CMS.Core.Interfaces;
using ComicMaster.CMS.Core.Models;
using ComicMaster.CMS.Web.Infrastructure;

using WebMatrix.WebData;

namespace ComicMaster.CMS.Web.Controllers
{
    public class DashBoardController : BaseController
    {
        #region Service calls
        private readonly IAuthorService _authorService;
        private readonly IAuthorTypeService _authorTypeService;
        private readonly IBlogService _blogService;
        private readonly IBookChapterService _bookChapterService;
        private readonly IBookService _bookService;
        private readonly ICategoryService _categoryService; 
        private readonly ICastService _castService;
        private readonly IChapterService _chapterService;
        private readonly IComicCastService _comicCastService;
        private readonly IComicService _comicService;
        private readonly ILinkService _linkService;
        private readonly IMediaLibraryService _mediaLibraryService;
        private readonly IMediaTypeService _mediaTypeService;
        private readonly IMembershipService _memberService;
        private readonly IMenuService _menuService;
        private readonly INewsService _newsService;
        private readonly IPostService _postService;
        private readonly IPostTagMapService _postTagMapService;
        private readonly IRoleService _roleService;
        private readonly ITagService _tagService;
        private readonly ITranscriptService _transcriptService;
        private readonly IUserService _userService;
        private readonly IUsersInRolesService _usersInRolesService;

        #endregion Service calls

        public DashBoardController()
            : this(new AuthorService(), new AuthorTypeService(), new BlogService(), new BookChapterService(), new BookService(), new CategoryService(), new CastService(), new ChapterService(), new ComicCastService(), new ComicService(), new LinkService(), new MediaLibraryService(), new MediaTypeService(), new MembershipService(), new MenuService(), new NewsService(), new PostService(), new PostTagMapService(), new RoleService(), new TagService(), new TranscriptService(), new UserService(), new UsersInRolesService())
        {
        }

        public DashBoardController(IAuthorService authorService, IAuthorTypeService authorTypeService, IBlogService blogService, IBookChapterService bookChapterService, IBookService bookService, ICategoryService categoryService, ICastService castService, IChapterService chapterService, IComicCastService comicCastService, IComicService comicService, ILinkService linkService, IMediaLibraryService mediaLibraryService, IMediaTypeService mediaTypeService, IMembershipService memberService, IMenuService menuservice, INewsService newsService, IPostService postService, IPostTagMapService postTagMapService, IRoleService roleService, ITagService tagService, ITranscriptService transcriptService, IUserService userService, IUsersInRolesService usersInRolesService)
        {
            _authorService = authorService;
            _authorTypeService = authorTypeService;
            _blogService = blogService;
            _bookChapterService = bookChapterService;
            _bookService = bookService;
            _categoryService = categoryService;
            _castService = castService;
            _chapterService = chapterService;
            _comicCastService = comicCastService;
            _comicService = comicService;
            _linkService = linkService;
            _mediaLibraryService = mediaLibraryService;
            _mediaTypeService = mediaTypeService;
            _memberService = memberService;
            _menuService = menuservice;
            _newsService = newsService;
            _postService = postService;
            _postTagMapService = postTagMapService;
            _roleService = roleService;
            _tagService = tagService;
            _transcriptService = transcriptService;
            _userService = userService;
            _usersInRolesService = usersInRolesService;
        }

        #region Articles
        public ActionResult Article(int id)
        {
            var news = _newsService.Single(n => n.NewsId == id);

            news.Comics = new List<dtoComic>(_comicService.GetAll());

            return View(news);
        }

        [HttpPost, ValidateInput(false)]
        [Authorize(Roles = "Administrator, Content Editor ")]
        [ValidateAntiForgeryToken]
        public ActionResult Article(dtoNews news, FormCollection form)
        {
            return View(news);
        }

        public ActionResult Articles()
        {
            return View();
        }

        public ActionResult AddArticles()
        {
            dtoNews news = new dtoNews();

            news.Comics = new List<dtoComic>(_comicService.GetAll());
            news.NewsDate = DateTime.Now;

            return View(news);
        }

        [HttpPost, ValidateInput(false)]
        [Authorize(Roles = "Administrator, Content Editor ")]
        [ValidateAntiForgeryToken]
        public ActionResult AddArticles(dtoNews news, FormCollection form)
        {
            return View(news);
        }
        #endregion Articles

        #region Authors
        [Authorize(Roles = "Administrator, Content Editor")]
        public ActionResult Account()
        {
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult AddAuthor()
        {
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Authors(int? id)
        {
            if (id.HasValue)
            {
                bool success = _memberService.DeleteRetBool(id.Value);
                if (success == true)
                    ViewData["Delete"] = Constants.Success;
                else
                    ViewData["Delete"] = Constants.Fail;
            }
            else
                ViewData["Delete"] = null;

            IList<dtoaspnet_Membership> _authors = _memberService.GetAll(a => a.IsApproved == true);

            if (_authors.Count > 0)
            {
                foreach (var author in _authors)
                {
                    author.aspnet_Users = new dtoaspnet_Users();

                    var user = _userService.Single(u => u.UserId == author.UserId);

                    if (user == null)
                    {
                    }
                    else
                        author.aspnet_Users.UserName = user.UserName;
                }

                return View(_authors);
            }
            else
            {
                return View(_authors);
            }            
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult CreateAccount()
        {
            dtoNewAccount model = new dtoNewAccount();
            var roles = _roleService.GetAll(r => r.RoleName != "Anonymous");
            var authorTypes = _authorTypeService.GetAll();

            model.AuthorTypes = new List<dtoAuthorType>();
            model.Roles = new Dictionary<string, string>();

            foreach (var authorType in authorTypes)
            {
                model.AuthorTypes.Add(authorType);
            }

            foreach(var role in roles)
            {
                model.Roles.Add(role.RoleId.ToString(), role.RoleName);
            }

            ViewData["Success"] = string.Empty;
            return View(model);
        }

        [HttpPost, ValidateInput(false)]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAccount(dtoNewAccount model, FormCollection collection)
        {
            bool OK = false;
            var _date = DateTime.Now;
            dtoaspnet_Users _model = new dtoaspnet_Users();

            _model.aspnet_UsersInRoles = new List<dtoaspnet_UsersInRoles>();
            _model.aspnet_Membership = new dtoaspnet_Membership();
            _model.aspnet_Membership.Author = new dtoAuthor();

            if (collection != null || collection.Count > 0)
            {
                model.Roles = new Dictionary<string, string>();

                if (collection[Constants.Administrator] != null)
                {
                    Guid newRole = new Guid(collection[Constants.Administrator]);

                    var adminRole = _roleService.Single(r => r.RoleId == newRole);

                    model.Roles.Add(adminRole.RoleId.ToString(), adminRole.RoleName);
                }

                if (collection[Constants.ContentEditor] != null)
                {
                    Guid newRole = new Guid(collection[Constants.ContentEditor]);

                    var contentEditor = _roleService.Single(r => r.RoleId == newRole);

                    model.Roles.Add(contentEditor.RoleId.ToString(), contentEditor.RoleName);
                }

                if (collection[Constants.AuthorSelectedType] != null)
                {
                    int aType = 0; 
                    string _atype = collection[Constants.AuthorSelectedType];

                    if (int.TryParse(_atype, out aType))
                    {
                        _model.aspnet_Membership.Author.AuthorType = aType;
                    }
                }
            }

            if (ModelState.IsValid)
            {
                _model.UserId = Guid.NewGuid();
                _model.UserName = model.UserName;
                _model.aspnet_Membership.FirstName = model.FirstName;
                _model.aspnet_Membership.LastName = model.LastName;
                _model.aspnet_Membership.Password = model.Password;

ComicMaster.CMS.Web/Controllers/MediaItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

using ComicMaster.CMS.Common.Infrastructure.Service;
using ComicMaster.CMS.Core;
using ComicMaster.CMS.Core.Interfaces;
using ComicMaster.CMS.Core.Models;

namespace ComicMaster.CMS.Web.Controllers
{
    public class MediaItemController : ApiController
    {
        private readonly IMediaLibraryService _mediaLibraryService;

        public MediaItemController()
            : this(new MediaLibraryService())
        {            
        }

        public MediaItemController(IMediaLibraryService mediaLibraryService)
        {
            _mediaLibraryService = mediaLibraryService;    
        }

        // GET api/mediaitem
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/mediaitem/5
        public string Get(int id)
        {
            return "value";
        }

        // DELETE api/mediaitem/5
        [HttpDelete]
        [AcceptVerbs("GET", "POST", "PUT", "DELETE")]
        [Authorize(Roles = "Administrator, Content Editor")]
        public HttpResponseMessage Delete(int id)
        {
            if (_mediaLibraryService.Delete(id))
                return new HttpResponseMessage(HttpStatusCode.OK);
            else
                return new HttpResponseMessage(HttpStatusCode.ExpectationFailed);
        }
    }
}

ComicMaster.CMS.Web/Views/DashBoard/AddChapter.cshtml
@model ComicMaster.CMS.Core.Models.dtoChapter

@using ComicMaster.CMS.Common;

@{
    ViewBag.Title = "Add a New Chapter";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<section id="widget-grid" class="">
    <div class="row-fluid">
        <article class="span12">
            <div class="jarviswidget" id="widget-1d-0" data-widget-fullscreenbutton="false" data-widget-editbutton="false" data-widget-deletebutton="false" data-widget-collapsed="false">
                <header>
                    New Chapter
                </header>
                <div>
                    <div class="inner-space">
                        @using (Html.BeginForm("AddChapter", "DashBoard", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
                            { 
                            <fieldset>
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true)
                                <div class="control-group">
                                    <label class="control-label" for="FirstName">Chapter Title</label>
                                    <div class="controls">
                                        @Html.TextBoxFor(model => model.ChapterTitle, new { @class = "span7", @name = "ChapterTitle", @id = "chapterTitle" })
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="Height">Slug</label>
                                    <div class="controls">
                                        @Html.TextBoxFor(model => model.ChapterSlug, new { @class = "span7", @name = "ChapterSlug", @id = "chapterSlug" })
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label"for="LastName">Book</label>
                                    <div class="controls">
                                        <select id="books" name="Books" class="span7"></select>
                                    </div>
                                </div>                                
                               <div class="form-actions">
									<button type="reset" class="btn medium btn-danger">
										Cancel
									</button>
									<button type="submit" class="btn medium btn-primary">
										Add Chapter
									</button>
								</div> 
                            </fieldset>
                            }
                    </div>
                </div>
            </div>
        </article>        
    </div>
</section>
<script type="text/javascript">
    //<!CDATA[
    "use strict";
    $(document).ready(function () {
            var options = {};
            options.url = "/api/book/get/";
            options.type = "GET";
            options.data = "";
            options.dataType = "json";
            options.contentType = "application/json";
            options.success = function (data) {
                $("#books").empty();
                $("#books").append("<option value='Select a book'>-- Select a book --</option>");
                for (var i = 0; i < data.data.length; i++) {
                    $("#books").append("<option value=" + data.data[i].BookID + ">" + data.data[i].BookTitle + "</option>");
                }
                $("#books").prop("disabled", false);
            };
            options.error = function () { alert("Error retrieving books!"); };
            $.ajax(options);
    });
    //]]>
</script>
@if (ViewData[Constants.AddStatus] == Constants.Success)
{
    <script type="text/javascript">
        //<!CDATA[
        "use strict";

        toastr.success('The new chapter has been added successfully.', 'Success!')
        //]]>
    </script>
}
else if (ViewData[Constants.AddStatus] == Constants.Fail)
{
    <script type="text/javascript">
        //<!CDATA[
        "use strict";
        toastr.error('There was a problem adding the new chapters!', 'Uh oh!')
        //]]>
    </script>
}
else
{
    
}

ComicMaster.CMS.Web/Views/DashBoard/AddLink.cshtml
@model ComicMaster.CMS.Core.Models.dtoLink

@{
    ViewBag.Title = "Add Link";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<section id="widget-grid" class="">
    <div class="row-fluid">
        <article class="span12">
            <div class="jarviswidget" id="widget-1d-0" data-widget-fullscreenbutton="false" data-widget-editbutton="false" data-widget-deletebutton="false" data-widget-collapsed="false">
                <header>
                    New External Link
                </header>
                <div>
                    <div class="inner-space">
                        @using (Html.BeginForm("AddLink", "DashBoard", FormMethod.Post, new { @class = "form-horizontal", @enctype = "multipart/form-data" }))
                            { 
                            <fieldset>
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true)
                                <div class="control-group">
                                    <label class="control-label" for="Alternate Name">Link Name</label>
                                    <div class="controls">
                                        @Html.TextBoxFor(model => model.AlternateName, new { @class = "span7", @name ="AlternateName", @id = "alternateName" })
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="URL">URL</label>
                                    <div class="controls">
                                        @Html.TextBoxFor(model => model.ExternalUrl, new { @class = "span7", @name = "ExternalUrl", @id = "externalUrl" })
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="ImagePath">Image</label>
                                    <div class="controls">                                       
                                        <input class="file" id="fileImage" type="file" name="ImagePath" /><br />
                                        @Html.ValidationMessageFor(m => m.ImagePath)
                                    </div>
                                </div>               
                               <div class="form-actions">
									<button type="reset" class="btn medium btn-danger">
										Cancel
									</button>
									<button type="submit" class="btn medium btn-primary">
										Add Link
									</button>
								</div> 
                            </fieldset>
                            }
                    </div>
                </div>
            </div>
        </article>        
    </div>
</section>

<script type="text/javascript">
    //<!CDATA[
    $(document).ready(function() {
        $.ajax({
            statusCode: {
                201: function (data) {
                    toastr.success('Your new link has been added to your collection.', 'Success!');
                },
                400: function (data) {
                    toastr.warning('No image was selected for the upload.', 'Missing Image.');
                },
                500: function (data) {
                    toastr.error('There was a problem adding the new link to your collection.', 'Uh-oh!');
                }
            }
        });
    });
    //]]>
</script>

ComicMaster.CMS.Web/Views/DashBoard/Blogs.cshtml
@model List<ComicMaster.CMS.Core.Models.dtoBlog>

@{
    ViewBag.Title = "Blogs";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<section id="widget-grid" class="">
    <div class="row-fluid">
        <article class="span12">
            <div class="jarviswidget" id="widget-id-0" data-widget-editbutton="false" data-widget-deletebutton="false" data-widget-collapsed="false">
                <header>
                    <h2>All Blogs</h2>
                </header>
                <div>
                    <div class="inner-spacer">
                        <div class="widget alert alert-success adjusted">
                            <a href="@Url.Action("AddBlog", "DashBoard")" class="btn btn-success">Add New</a>
                        </div>
                        <table class="table table-striped table-bordered responsive" id="col-filter">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Slug</th>
                                    <th>Post Count</th>
                                    <th>Active</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody id="bootbox-js">
                                @for (int i = 0; i < Model.Count; i++)
                                {
                                    <tr class="@(i % 2 == 1 ? "even" : "odd")">
                                        <td><a href="@Url.Action("Posts", "DashBoard", new { @id = Model[i].Id })">@Html.Raw(Model[i].BlogTitle)</a></td>
                                        <td>@Html.Raw(Model[i].BlogSlug)</td>
                                        <td style="text-align:center;">@Html.Raw(Model[i].PostCount)</td>
                                        @if (Model[i].Active == true)
                                        {
                                            <td style="text-align:center;"><input type="checkbox" name="Active" id="Active" checked="checked" /></td>
                                        }
                                        else
                                        {
                                            <td style="text-align:center;"><input type="checkbox" name="Active" id="Active" checked="" /></td>
                                        }
                                        <td style="text-align:center;"><a href="@Url.Action("Blog", "DashBoard", new {@id = Model[i].Id })" class="btn btn-primary btn-small">Edit</a> | <a href="javascript:void(0);" onclick="deleteBlog(@Model[i].Id.ToString())" id="bootbox-confirm-js" class="btn btn-primary btn-small">Delete</a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </article>
    </div>
</section>
<script type="text/javascript">
    //<!CDATA[
    "use strict";
    function deleteBlog(id)
    {
        bootbox.confirm("Are you sure you want to delete this blog?", function (result) {
            if (result) {
                $(".loading").removeClass("hidden");

                $.ajax({
                    url: "/api/blog/delete/" + id,
                    type: 'DELETE',
                    statusCode: {
                        204: function () {
                            $(".loading").addClass("hidden");
                            toastr.success('The blog has been deleted successfully.', 'Success!');
                            document.location.reload(true);
                        },
                        417: function () {
                            $(".loading").addClass("hidden");
                            toastr.error('There was a problem deleting the blog.', 'Uh-oh!');
                        }
                    }
                });
            }
            else {
                event.preventDefault();
            }
        });
    }
    //]]>
</script>

ComicMaster.CMS.Web/Views/DashBoard/RightMenu.cshtml
@{
    Layout = null;
}

<aside class="right">					
	<!-- date picker -->
	<div id="datepicker"></div>
	<div class="divider"></div>
	<!-- end date picker -->
    <!-- aside buttons -->
	<div class="aside-buttons">
        @Html.ActionLink("Add New Book", "AddBook", "DashBoard", null, new { @class = "btn btn-success" })
        @Html.ActionLink("Add New Chapter", "AddChapter", "DashBoard", null, new { @class = "btn btn-danger" })
        @Html.ActionLink("Add New Character", "AddCast", "Dashboard", null, new { @class = "btn btn-warning" }) 
        @Html.ActionLink("Add New Comic", "AddComic", "DashBoard", null, new { @class = "btn btn-info" })
        @Html.ActionLink("Add Transcript", "AddTranscript", "Dashboard", null, new { @class = "btn purple-btn" })
	</div>
	<div class="divider"></div>
	<!-- end aside buttons -->
</aside>